### ISSUE TITLE
Can you share the code for upload.php? 

### ISSUE THREAD

**Issue by baymaxing** [Formstone/Dropper#6]
I downloaded the code, Everything works great. However in index.html if I change the action to pointing to upload.php in the local folder (on here in demo folder)instead of the remote link.

$(".demo .dropped").dropper({
					action: "http://formstone.it/components/Dropper/demo/upload.php",
					maxSize: 1048576
I got errors all the time the queue list. Could you shed some lights for this? Thanks a lot!

**Comment by benplum** [comment]
Are you serving the local file over mamp? You can't execute a .php without a web server.

**Comment by baymaxing** [comment]
Thanks for your quick response.:) I did use apache tomcat and put the code under webapp. I access the homepage from my localhost. Drag works perfect. However when it tries upload. At the queue list, it just dumped out the error which basically throw out the code from upload.php. I could not see the process.

**Comment by benplum** [comment]
It sounds like the script isn't executing. Not sure how to help you diagnose it further.

**Comment by baymaxing** [comment]
Hey, thanks a lot anyway. Somehow the php script didn't get processed. I fixed it by using js to take care of the uploads.
